Repository MicrosoftDocs/architecture-center, pull requests merged in 2019-10, with the labels that each got.

#1804 Fixing formatting
  docs/reference-architectures/iot/index.md
Labels: Change sent to author, architecture-center/svc, do-not-merge, reference-architecture/subsvc

#1811 Remove fragment per loc US 1612605.
  docs/security/network-security-containment.md
Labels: Change sent to author, architecture-center/svc, assessing_(C&L), cloud-design-principles/subsvc, do-not-merge

#1810 Localization fixes - punctuation and typo
  docs/security/governance.md
Labels: Change sent to author, architecture-center/svc, assessing_(C&L), cloud-design-principles/subsvc, do-not-merge

#1815 Update mobile section to mention App Center
  docs/aws-professional/services.md
Labels: Change sent to author, architecture-center/svc, cloud-fundamentals/subsvc, do-not-merge

#1822 Fix typo
  docs/guide/index.md
Labels: Change sent to author, architecture-center/svc, do-not-merge, reference-architecture/subsvc
