Repository MicrosoftDocs/architecture-center, pull requests merged in 2019-11, with the labels that each got.

#1837 fix typo RetryPolicty
  docs/best-practices/retry-service-specific.md
Labels: Change sent to author, architecture-center/svc, assessing_(C&L), cloud-fundamentals/subsvc, do-not-merge

#1836 (AzureCXP) MicrosoftDocs/architecture-center#1832
  docs/data-guide/technology-choices/analytical-data-stores.md
Labels: Change sent to author, architecture-center/svc, assessing_(C&L), cloud-fundamentals/subsvc, do-not-merge

#1839 Update index.md
  docs/index.md
Labels: assessing_(C&L), do-not-merge, review-team-triage

#1818 Update caching.md fix typo
  docs/best-practices/caching.md
Labels: Change sent to author, architecture-center/svc, assessing_(C&L), cloud-fundamentals/subsvc, do-not-merge

#1833 Updated modernize-app-azure-service-fabric.md
  docs/service-fabric/modernize-app-azure-service-fabric.md
Labels: Change sent to author, architecture-center/svc, assessing_(C&L), do-not-merge, reference-architecture/subsvc

#1824 Knowledge to Decision in Cognitive Services
  docs/data-guide/technology-choices/cognitive-services.md
Labels: Change sent to author, architecture-center/svc, assessing_(C&L), cloud-fundamentals/subsvc, do-not-merge

#1863 fixed “point-to-point” hyphenation under Benefits
  docs/guide/architecture-styles/event-driven.md
Labels: Change sent to author, architecture-center/svc, assessing_(C&L), cloud-fundamentals/subsvc, do-not-merge
