Repository MicrosoftDocs/architecture-center, pull requests merged in 2019-04, with the labels that each got.

#1484 typo: Aquire -> Acquire
  docs/patterns/leader-election.md
Labels: Change sent to author, architecture-center/svc, cloud-fundamentals/subsvc, do-not-merge

#1430 fix: MD037/no-space-in-emphasis
  docs/cloud-adoption/governance/policy-compliance/risk-tolerance.md
Labels: Change sent to author, do-not-merge

#1496 fix: MD009/no-trailing-spaces
  contributing-to/templates/sample-solution.md
  docs/cloud-adoption/decision-guides/resource-consistency/overview.md
  docs/cloud-adoption/governance/resource-consistency/template.md
  docs/data-guide/technology-choices/analytical-data-stores.md
  docs/databricks-monitoring/dashboards.md
  docs/example-scenario/ai/newsfeed-ingestion.md
  docs/microservices/design/interservice-communication.md
  docs/microservices/introduction.md
  docs/patterns/publisher-subscriber.md
  docs/reference-architectures/ai/batch-scoring-python.md
  docs/reference-architectures/ai/conversational-bot.md
  docs/reference-architectures/ai/realtime-scoring-python.md
  docs/reference-architectures/ai/training-python-models.md
  docs/reference-architectures/data/enterprise-bi-adf.md
  docs/reference-architectures/microservices/aks.md
  docs/reference-architectures/n-tier/linux-vm.md
  docs/reference-architectures/n-tier/windows-vm.md
  docs/reliability/index.md
  docs/service-fabric/migrate-from-cloud-services.md
Labels: Change sent to author, architecture-center/svc, ready-to-merge, reference-architecture/subsvc

#1018 added link to microservices page
  docs/example-scenario/data/ecommerce-order-processing.md
Labels: Change sent to author, do-not-merge

#1516 fix: MD022/blanks-around-headings/blanks-around-headers
  docs/reference-architectures/microservices/service-fabric.md
Labels: Change sent to author, architecture-center/svc, do-not-merge, reference-architecture/subsvc

#1519 Fix missing markup end quote (`)
  docs/patterns/scheduler-agent-supervisor.md
Labels: Change sent to author, architecture-center/svc, cloud-fundamentals/subsvc, do-not-merge

#1526 Update minimum Databricks version
  docs/databricks-monitoring/configure-cluster.md
Labels: Change sent to author, do-not-merge

#1376 Clarification
  docs/cloud-adoption/migrate/azure-best-practices/migrate-best-practices-networking.md
Labels: Change sent to author, azure-migrate/svc, do-not-merge

#1528 Migration guide review
  docs/cloud-adoption/migrate/azure-migration-guide/assess.md
  docs/cloud-adoption/migrate/azure-migration-guide/assistance.md
  docs/cloud-adoption/migrate/azure-migration-guide/index.md
  docs/cloud-adoption/migrate/azure-migration-guide/manage-costs.md
  docs/cloud-adoption/migrate/azure-migration-guide/migrate.md
  docs/cloud-adoption/migrate/azure-migration-guide/optimize-and-transform.md
  docs/cloud-adoption/migrate/azure-migration-guide/organize-resources.md
  docs/cloud-adoption/migrate/azure-migration-guide/prerequisites.md
  docs/cloud-adoption/migrate/azure-migration-guide/secure-and-manage.md
Labels: Change sent to author, azure-portal/svc, do-not-merge
