Repository MicrosoftDocs/architecture-center, pull requests merged in 2019-06, with the labels that each got.

#1578 Removed an extraneous apostrophe
  docs/example-scenario/apps/telehealth-system.md
Labels: Change sent to author, architecture-center/svc, do-not-merge, example-scenario/subsvc

#1577 Updated formatting and added a space
  docs/example-scenario/apps/telehealth-system.md
Labels: Change sent to author, architecture-center/svc, do-not-merge, example-scenario/subsvc

#1579 Suggest to clear code block
  docs/multitenant-identity/key-vault.md
Labels: Change sent to author, architecture-center/svc, do-not-merge, reference-architecture/subsvc

#1576 Fixing typos
  docs/example-scenario/apps/telehealth-system.md
Labels: Change sent to author, architecture-center/svc, example-scenario/subsvc, ready-to-merge

#1581 Fix line 99 typo
  docs/cloud-adoption/getting-started/migrate.md
Labels: Change sent to author, do-not-merge

#1582 Fix broken link & update old MSDN links to Docs.
  docs/patterns/cqrs.md
Labels: Change sent to author, architecture-center/svc, cloud-fundamentals/subsvc, do-not-merge

#1590 Edited Duplicate content
  docs/cloud-adoption/decision-guides/migrate-decision-guide/index.md
Labels: Change sent to author, do-not-merge

#1586 Removed controversial section
  docs/reference-architectures/hybrid-networking/shared-services.md
Labels: Change sent to author, architecture-center/svc, do-not-merge, reference-architecture/subsvc

#1601 changing `now` to `how`.
  docs/reliability/index.md
Labels: Change sent to author, architecture-center/svc, cloud-design-principles/subsvc, ready-to-merge

#1460 Adapting to upcoming Portal UI changes on App Registration
  docs/multitenant-identity/run-the-app.md
Labels: Change sent to author, architecture-center/svc, ready-to-merge, reference-architecture/subsvc

#1605 fix invalid link to StackExchange.Redis docs
  docs/best-practices/caching.md
Labels: Change sent to author, architecture-center/svc, cloud-fundamentals/subsvc, do-not-merge

#1078 Add vulnerability scanning of running containers
  docs/reference-architectures/microservices/aks.md
Labels: Change sent to author, ready-to-merge

#1617 Update cqrs.md
  docs/patterns/cqrs.md
Labels: Change sent to author, architecture-center/svc, cloud-fundamentals/subsvc, do-not-merge

#1520 (AzureCXP) mention outgoing traffic rules
  docs/reference-architectures/identity/adds-extend-domain.md
Labels: Change sent to author, architecture-center/svc, do-not-merge, reference-architecture/subsvc

#1618 Typo fix
  docs/data-guide/relational-data/etl.md
Labels: Change sent to author, architecture-center/svc, cloud-fundamentals/subsvc, do-not-merge
