Repository MicrosoftDocs/architecture-center, pull requests merged in 2020-07, with the labels that each got.

#2203 Update chaos-engineering.md
  docs/framework/resiliency/chaos-engineering.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, do-not-merge, well-architected/subsvc

#2209 Updated statement
  docs/framework/cost/overview.md
Labels: Change sent to author, architecture-center/svc, do-not-merge, well-architected/subsvc

#2220 Adding <> for bare URL
  docs/reference-architectures/data/stream-processing-stream-analytics.md
Labels: Change sent to author, architecture-center/svc, do-not-merge, reference-architecture/subsvc

#2223 Update remote-patient-monitoring.md
  docs/solution-ideas/articles/remote-patient-monitoring.md
Labels: Change sent to author, architecture-center/svc, do-not-merge, solution-idea/subsvc

#2219 Replacing with "opaque box"
  docs/microservices/design/gateway.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, ready-to-merge, reference-architecture/subsvc

#2221 Deleting internal comment/question
  docs/reference-architectures/identity/adfs.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, do-not-merge, reference-architecture/subsvc

#2224 Azure AD Basic was replaced by Office 365 Apps
  docs/reference-architectures/identity/azure-ad.md
Labels: Change sent to author, architecture-center/svc, ready-to-merge, reference-architecture/subsvc

#2226 Fix capitalization of .NET
  docs/data-guide/technology-choices/data-storage.md
Labels: Change sent to author, architecture-center/svc, cloud-fundamentals/subsvc, do-not-merge

#2199 Update chaos-engineering.md
  docs/framework/resiliency/chaos-engineering.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, ready-to-merge, well-architected/subsvc

#2231 Update iiot-architecture.md
  docs/guide/iiot-guidance/iiot-architecture.md
Labels: Change sent to author, architecture-center/svc, do-not-merge, reference-architecture/subsvc

#2232 Update iiot-services.md
  docs/guide/iiot-guidance/iiot-services.md
Labels: Change sent to author, architecture-center/svc, do-not-merge, reference-architecture/subsvc

#2233 Update iiot-data.md
  docs/guide/iiot-guidance/iiot-data.md
Labels: Change sent to author, architecture-center/svc, do-not-merge, reference-architecture/subsvc

#2234 Update iiot-considerations.md
  docs/guide/iiot-guidance/iiot-considerations.md
Labels: Change sent to author, architecture-center/svc, do-not-merge, reference-architecture/subsvc

#2235 Update windows-virtual-desktop.md
  docs/example-scenario/wvd/windows-virtual-desktop.md
Labels: Change sent to author, architecture-center/svc, do-not-merge, example-scenario/subsvc

#2244 Make Note content part of the alert
  docs/patterns/sharding.md
Labels: Change sent to author, architecture-center/svc, cloud-fundamentals/subsvc, do-not-merge

#2241 Correction of typo
  docs/guide/design-principles/design-for-operations.md
Labels: Change sent to author, architecture-center/svc, do-not-merge, reference-architecture/subsvc

#2253 Update windows-virtual-desktop.md
  docs/example-scenario/wvd/windows-virtual-desktop.md
Labels: Change sent to author, architecture-center/svc, example-scenario/subsvc, ready-to-merge

#2254 Remove en-us for build to validate
  docs/example-scenario/wvd/windows-virtual-desktop.md
Labels: Change sent to author, architecture-center/svc, example-scenario/subsvc, ready-to-merge

#2256 Wrong url for resource limits sample
  docs/framework/devops/app-design.md
Labels: Change sent to author, architecture-center/svc, do-not-merge, well-architected/subsvc

#2260 Updated the link for the pricing estimate
  docs/solution-ideas/articles/cicd-for-containers.md
Labels: Change sent to author, architecture-center/svc, do-not-merge, solution-idea/subsvc

#2264 fix broken link to Azure Well-Architected Framework
  docs/reference-architectures/containers/aks/secure-baseline-aks.md
Labels: Change sent to author, architecture-center/svc, do-not-merge, reference-architecture/subsvc

#2276 Correction in terminology
  docs/framework/scalability/monitoring.md
Labels: Change sent to author, architecture-center/svc, do-not-merge, well-architected/subsvc

#2281 Update windows-virtual-desktop.md
  docs/example-scenario/wvd/windows-virtual-desktop.md
Labels: Change sent to author, architecture-center/svc, example-scenario/subsvc, ready-to-merge

#2279 update deprecated 'group deployment' to 'deployment group'
  docs/building-blocks/extending-templates/objects-as-parameters.md
Labels: Change sent to author, architecture-center/svc, do-not-merge, reference-architecture/subsvc

#2278 update deprecated "group deployment" to "deployment group"
  docs/building-blocks/extending-templates/conditional-deploy.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, do-not-merge, reference-architecture/subsvc

#2277 update deprecated 'group deployment' to 'deployment group'
  docs/building-blocks/extending-templates/update-resource.md
Labels: Change sent to author, architecture-center/svc, do-not-merge, reference-architecture/subsvc

#2280 update deprecated 'group deployment' to 'deployment group'
  docs/building-blocks/extending-templates/collector.md
Labels: Change sent to author, architecture-center/svc, do-not-merge, reference-architecture/subsvc
