Repository MicrosoftDocs/architecture-center, pull requests merged in 2020-03, with the labels that each got.

#2001 Grammar
  docs/patterns/publisher-subscriber.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, cloud-fundamentals/subsvc, do-not-merge

#1994 Add PrivateLink
  docs/aws-professional/services.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, cloud-fundamentals/subsvc, do-not-merge

#1997 renaming azure search to azure cognitive search
  docs/reference-architectures/app-service-web-app/scalable-web-app.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, do-not-merge, reference-architecture/subsvc

#2002 Fix typos
  docs/aws-professional/services.md
Labels: Change sent to author, architecture-center/svc, cloud-fundamentals/subsvc, do-not-merge

#2004 Update MLOps Python article with additional info from microsoft/MLOpsPython
  docs/reference-architectures/ai/mlops-python.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, do-not-merge, reference-architecture/subsvc

#2000 Grammar
  docs/patterns/choreography.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, cloud-fundamentals/subsvc, do-not-merge

#1995 Update network-security-containment.md
  docs/framework/security/network-security-containment.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, cloud-design-principles/subsvc, do-not-merge

#2036 Typo corrected
  docs/best-practices/transient-faults.md
Labels: Change sent to author, architecture-center/svc, cloud-fundamentals/subsvc, do-not-merge

#2038 Fix VM SKU typo
  docs/example-scenario/infrastructure/reservoir-simulation.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, do-not-merge, example-scenario/subsvc

#2041 Add dot
  docs/best-practices/data-partitioning-strategies.md
Labels: Change sent to author, architecture-center/svc, cloud-fundamentals/subsvc, do-not-merge
