Repository MicrosoftDocs/architecture-center, pull requests merged in 2020-10, with the labels that each got.

#2422 Update ms.date: 09/10/2020
  docs/reference-architectures/iot.md
Labels: Change sent to author, architecture-center/svc, do-not-merge, reference-architecture/subsvc

#2421 Update chaos-engineering.md
  docs/framework/resiliency/chaos-engineering.md
Labels: Change sent to author, architecture-center/svc, do-not-merge, well-architected/subsvc

#2411 Remove reference to DTL
  docs/solution-ideas/articles/dev-test-paas.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, ready-to-merge, solution-idea/subsvc

#2434 Update application-logs.md
  docs/databricks-monitoring/application-logs.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, do-not-merge, reference-architecture/subsvc

#2400 Add missing link for devops-monitoring
  docs/reference-architectures/app-service-web-app/app-monitoring.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, do-not-merge, reference-architecture/subsvc

#2410 Add AD Domain Services link
  docs/example-scenario/infrastructure/linux-vdi-citrix.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, do-not-merge, example-scenario/subsvc

#2446 FIX: typo (`retrieves` -> `retrieved`)
  docs/guide/technology-choices/data-store-overview.md
Labels: Change sent to author, architecture-center/svc, do-not-merge, reference-architecture/subsvc

#2454 Elanzel architecture center
  docs/example-scenario/forensics/index.md
Labels: Change sent to author, architecture-center/svc, ready-to-merge

#2457 Spell - Ulta -Update load-balancing-overview.md
  docs/guide/technology-choices/load-balancing-overview.md
Labels: Change sent to author, architecture-center/svc, do-not-merge, reference-architecture/subsvc
