Repository MicrosoftDocs/architecture-center, pull requests merged in 2020-02, with the labels that each got.

#1972 Update reference to 'nginScript' to use new name
  docs/microservices/design/gateway.md
Labels: Change sent to author, architecture-center/svc, assessing_(C&L), do-not-merge, reference-architecture/subsvc

#1975 add fcp metadata
  docs/topics/high-performance-computing.md
Labels: Change sent to author, architecture-center/svc, do-not-merge

#1973 Add Azure NetApp Files to Storage
  docs/topics/high-performance-computing.md
Labels: Change sent to author, architecture-center/svc, assessing_(C&L), do-not-merge

#1961 Remove unnecessary commas
  docs/guide/technology-choices/messaging.md
Labels: Change sent to author, architecture-center/svc, assessing_(C&L), do-not-merge, reference-architecture/subsvc

#1956 Update gitflow-branch-workflow.md
  docs/framework/devops/gitflow-branch-workflow.md
Labels: Change sent to author, architecture-center/svc, assessing_(C&L), cloud-design-principles/subsvc, do-not-merge

#1978 Update external-configuration-store.md
  docs/patterns/external-configuration-store.md
Labels: Change sent to author, architecture-center/svc, assessing_(C&L), cloud-fundamentals/subsvc, do-not-merge

#1992 Update cqrs.md
  docs/patterns/cqrs.md
Labels: Change sent to author, architecture-center/svc, assessing_(C&L), cloud-fundamentals/subsvc, do-not-merge

#1996 Update cqrs.md
  docs/patterns/cqrs.md
Labels: Change sent to author, architecture-center/svc, cloud-fundamentals/subsvc, do-not-merge
