Repository MicrosoftDocs/architecture-center, pull requests merged in 2021-08, with the labels that each got.

#2983 Update select-features.md
  docs/data-science-process/select-features.md
Labels: Change sent to author, aq-pr-triaged, machine-learning/svc, ready-to-merge, team-data-science-process/subsvc

#2984 Update services.md
  docs/gcp-professional/services.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, cloud-fundamentals/subsvc, ready-to-merge

#2990 End User Computing Services Comparison
  docs/aws-professional/services.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, cloud-fundamentals/subsvc, do-not-merge

#2982 Update services.md
  docs/gcp-professional/services.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, cloud-fundamentals/subsvc, ready-to-merge

#2958 Update accounts.md
  docs/aws-professional/accounts.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, cloud-fundamentals/subsvc, do-not-merge

#3002 Update index.md
  docs/gcp-professional/index.md
Labels: Change sent to author, architecture-center/svc, cloud-fundamentals/subsvc, do-not-merge

#3000 Added Azure Flexible Database Details
  docs/gcp-professional/services.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, cloud-fundamentals/subsvc, aq-pr-triaged

#2967 Updated Big Data and Analytics and added ADB
  docs/gcp-professional/services.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, cloud-fundamentals/subsvc, aq-pr-triaged

#2963 Update services.md
  docs/aws-professional/services.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, cloud-fundamentals/subsvc, aq-pr-triaged

#2979 Update services.md
  docs/gcp-professional/services.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, cloud-fundamentals/subsvc, aq-pr-triaged

#2978 Update services.md
  docs/gcp-professional/services.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, cloud-fundamentals/subsvc, aq-pr-triaged

#2994 Update services.md
  docs/gcp-professional/services.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, cloud-fundamentals/subsvc, aq-pr-triaged

#2995 Update services.md
  docs/gcp-professional/services.md
Labels: Change sent to author, ready-to-merge, architecture-center/svc, cloud-fundamentals/subsvc, aq-pr-triaged

#2999 Replace Data Catalog with Azure Purview
  docs/aws-professional/services.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, cloud-fundamentals/subsvc, aq-pr-triaged

#3007 Correct a word on line 56
  docs/framework/security/design-management-groups.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, well-architected/subsvc

#2961 Update networking.md
  includes/aws/networking.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, aq-pr-triaged

#2991 Update messaging.md
  docs/aws-professional/messaging.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, cloud-fundamentals/subsvc, aq-pr-triaged

#2959 Update compute.md
  docs/aws-professional/compute.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, cloud-fundamentals/subsvc, aq-pr-triaged

#3009 Resolve syncing conflicts from repo_sync_working_branch to master
  docs/aws-professional/databases.md
  docs/changelog.md
  docs/example-scenario/mainframe/migrate-unisys-dorado-mainframe-apps-with-astadia-micro-focus-content.md
  docs/example-scenario/precision-medicine/genomic-analysis-reporting-content.md
  docs/example-scenario/sql-failover/sql-failover-2008r2-content.md
  docs/feed.atom
  docs/gcp-professional/index.md
  docs/gcp-professional/services.md
  docs/reference-architectures/migration/modernize-mainframe-data-to-azure-content.md
  docs/solution-ideas/articles/mainframe-access-azure-databases-content.md
Labels: do-not-merge, review-team-triage

#2962 Update databases.md
  docs/aws-professional/databases.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, cloud-fundamentals/subsvc, aq-pr-triaged

#2997 Multiple updates
  docs/aws-professional/databases.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, cloud-fundamentals/subsvc, aq-pr-triaged

#2998 Added link for MariaDB
  includes/aws/databases.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, aq-pr-triaged

#3003 Update networking.md
  docs/aws-professional/networking.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, cloud-fundamentals/subsvc, aq-pr-triaged

#3020 Add link to CSI secrets store doc
  docs/reference-architectures/containers/aks/secure-baseline-aks-content.md
Labels: do-not-merge, review-team-triage

#3029 Grammar and spelling issues
  docs/framework/security/governance.md
  docs/framework/security/monitor-test.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, well-architected/subsvc

#3031 Updates
  docs/framework/scalability/design-distributed.md
  docs/framework/scalability/monitor-analyze.md
  docs/framework/scalability/monitor-infrastructure.md
  docs/framework/scalability/monitor.md
  docs/framework/scalability/optimize-partition.md
  docs/framework/scalability/optimize.md
  docs/framework/scalability/performance-efficiency-patterns.md
  docs/framework/scalability/principles.md
  docs/framework/scalability/test-tools.md
  docs/framework/scalability/tradeoffs.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, well-architected/subsvc

#3033 Updates
  docs/framework/hybrid/hybrid-cost.md
  docs/framework/hybrid/hybrid-opex.md
  docs/framework/hybrid/hybrid-overview.md
  docs/framework/hybrid/hybrid-performance-efficiency.md
  docs/framework/hybrid/hybrid-reliability.md
  docs/framework/hybrid/hybrid-security.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, well-architected/subsvc
