Repository MicrosoftDocs/architecture-center, pull requests merged in 2021-01, with the labels that each got.

#2580 Fix typo Continious to Continuous
  docs/framework/devops/release-engineering-ci.md
Labels: Change sent to author, architecture-center/svc, do-not-merge, well-architected/subsvc

#2583 Corrected a grammar error on stream-processing.md
  docs/data-guide/technology-choices/stream-processing.md
Labels: Change sent to author, architecture-center/svc, azure-guide/subsvc, do-not-merge

#2586 Update design-segmentation.md
  docs/framework/security/design-segmentation.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, do-not-merge, well-architected/subsvc

#2615 Update index.md
  docs/icons/index.md
Labels: Change sent to author, architecture-center/svc, do-not-merge

#2611 Added docs for MDM in Azure with Profisee
  docs/browse/thumbs/mdm-in-azure-with-profisee.png
  docs/reference-architectures/data/images/example-adf-template.jpg
  docs/reference-architectures/data/images/mdm-profisee-data-flow.png
  docs/reference-architectures/data/images/mdm-profisee-integration-pipeline.png
  docs/reference-architectures/data/images/rest-sync-to-profisee.jpg
  docs/reference-architectures/data/images/source-json-data.jpg
  docs/reference-architectures/data/mdm-in-azure-with-profisee-content.md
  docs/reference-architectures/data/mdm-in-azure-with-profisee.yml
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, do-not-merge
