Repository MicrosoftDocs/architecture-center, pull requests merged in 2021-12, with the labels that each got.

#3203 Added link to new Azure Load Testing preview
  docs/framework/scalability/load-testing.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, well-architected/subsvc

#3227 Remove duplicate items from Microsoft Defender for Cloud References
  docs/hybrid/hybrid-security-monitoring-content.md
Labels: do-not-merge, review-team-triage

#3230 Name of the service is: Event Hubs
  includes/aws/messaging.md
Labels: Change sent to author, do-not-merge, architecture-center/svc
