Repository MicrosoftDocs/architecture-center, pull requests merged in 2021-03, with the labels that each got.

#2711 Updates on Using Azure file shares in a hybrid environment
  docs/hybrid/azure-file-share-content.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, do-not-merge

#2716 Corrected typo sale on demand
  docs/framework/hybrid/hybrid-cost.md
Labels: Change sent to author, architecture-center/svc, do-not-merge, well-architected/subsvc

#2731 Resolve syncing conflicts from repo_sync_working_branch to master
  docs/antipatterns/retry-storm/index.md
  docs/checklist/resiliency-per-service.md
  docs/example-scenario/ai/intelligent-apps-image-processing-content.md
  docs/example-scenario/apps/sap-on-oracle-content.md
  docs/example-scenario/gateway/firewall-application-gateway-content.md
  docs/example-scenario/integration/logic-apps-data-integration-content.md
  docs/example-scenario/mainframe/micro-focus-server-content.md
  docs/example-scenario/private-web-app/private-web-app-content.md
  docs/example-scenario/sql-failover/app-service-private-sql-multi-region-content.md
  docs/framework/hybrid/hybrid-cost.md
  docs/framework/hybrid/hybrid-opex.md
  docs/framework/hybrid/hybrid-overview.md
  docs/framework/hybrid/hybrid-performance-efficiency.md
  docs/framework/hybrid/hybrid-reliability.md
  docs/framework/hybrid/hybrid-security.md
  docs/framework/resiliency/app-design-error-handling.md
  docs/framework/resiliency/app-design.md
  docs/framework/resiliency/backup-and-recovery.md
  docs/framework/resiliency/chaos-engineering.md
  docs/framework/resiliency/design-best-practices.md
  docs/framework/resiliency/design-checklist.md
  docs/framework/resiliency/design-requirements.md
  docs/framework/resiliency/design-resiliency.md
  docs/framework/resiliency/monitor-checklist.md
  docs/framework/resiliency/monitor-model.md
  docs/framework/resiliency/monitoring.md
  docs/framework/resiliency/overview.md
  docs/framework/resiliency/test-best-practices.md
  docs/framework/resiliency/test-checklist.md
  docs/framework/resiliency/testing.md
  docs/guide/technology-choices/images/load-balancing-help-me-choose.png
  docs/guide/technology-choices/load-balancing-overview.md
  docs/high-availability/reference-architecture-traffic-manager-application-gateway.md
  docs/reference-architectures/ai/realtime-scoring-r-content.md
  docs/reference-architectures/aws/aws-azure-ad-security-content.md
  docs/reference-architectures/dmz/secure-vnet-dmz-content.md
  docs/reference-architectures/sap/sap-netweaver-content.md
  docs/reference-architectures/sap/sap-s4hana-content.md
  docs/solution-ideas/articles/data-storage-edge-content.md
  docs/solution-ideas/articles/interactive-voice-response-bot-content.md
  docs/solution-ideas/articles/machine-learning-with-aks-content.md
  docs/solution-ideas/articles/messaging-content.md
  docs/solution-ideas/articles/personalized-offers-content.md
  docs/solution-ideas/articles/population-health-management-for-healthcare-content.md
  docs/solution-ideas/articles/predicting-length-of-stay-in-hospitals-content.md
  docs/solution-ideas/articles/predictive-maintenance-content.md
  docs/solution-ideas/articles/product-recommendations-content.md
  docs/solution-ideas/articles/retail-and-e-commerce-using-cosmos-db-content.md
  docs/solution-ideas/articles/speech-services-content.md
  docs/solution-ideas/articles/visual-assistant-content.md
  docs/toc.yml
Labels: do-not-merge

#2732 Added PS Script for Defender AV Exclusions
  docs/example-scenario/wvd/windows-virtual-desktop-fslogix-content.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, do-not-merge, review-team-triage

#2734 Removed reference to doAzureParallel.
  docs/data-guide/technology-choices/r-developers-guide.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, cloud-fundamentals/subsvc, do-not-merge
