Repository MicrosoftDocs/architecture-center, pull requests merged in 2021-04, with the labels that each got.

#2749 Update backup-and-recovery.md
  docs/framework/resiliency/backup-and-recovery.md
Labels: Change sent to author, architecture-center/svc, do-not-merge, well-architected/subsvc

#2756 Fix typo in design-checklist.md
  docs/framework/resiliency/design-checklist.md
Labels: Change sent to author, architecture-center/svc, do-not-merge, well-architected/subsvc

#2755 Update microservices-intro.md
  docs/includes/microservices-intro.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, do-not-merge, guide/subsvc

#2766 Update design-network-endpoints.md
  docs/framework/security/design-network-endpoints.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, do-not-merge, well-architected/subsvc

#2792 Removed an extra `messages`
  docs/best-practices/message-encode.md
Labels: Change sent to author, architecture-center/svc, best-practice/subsvc, do-not-merge
