Repository MicrosoftDocs/architecture-center, pull requests merged in 2021-11, with the labels that each got.

#3139 Update aks-start-here.md
  docs/reference-architectures/containers/aks-start-here.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, reference-architecture/subsvc, aq-pr-triaged

#3161 Update raincode-reference-architecture-content.md
  docs/reference-architectures/app-modernization/raincode-reference-architecture-content.md
Labels: do-not-merge, review-team-triage

#3160 Update refactor-zos-coupling-facility-content.md
  docs/reference-architectures/zos/refactor-zos-coupling-facility-content.md
Labels: do-not-merge, review-team-triage

#3179 Update sharding.md
  docs/patterns/sharding.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, design-pattern/subsvc

#3166 Fixed content in vision-classifier-model-with-custom-vision-content.md
  docs/example-scenario/dronerescue/vision-classifier-model-with-custom-vision-content.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, aq-pr-triaged

#3190 Update release-engineering-performance.md
  docs/framework/devops/release-engineering-performance.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, well-architected/subsvc
