Repository MicrosoftDocs/architecture-center, pull requests merged in 2021-07, with the labels that each got.

#2869 Added Services to create Landing Zone
  docs/aws-professional/services.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, cloud-fundamentals/subsvc, do-not-merge

#2827 Update messaging.md
  includes/aws/messaging.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, ready-to-merge

#2901 Update design-requirements.md
  docs/framework/resiliency/design-requirements.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, do-not-merge, well-architected/subsvc

#2818 Update index.md
  docs/guide/index.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, do-not-merge, guide/subsvc

#2880 Update government.md
  docs/industries/government.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, do-not-merge

#2846 Typo "Azure blob storage"→"Azure Blob Storage"
  docs/best-practices/data-partitioning-strategies.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, best-practice/subsvc, do-not-merge

#2815 Update design-governance.md
  docs/framework/cost/design-governance.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, do-not-merge, well-architected/subsvc

#2904 Add Bicep to list of CloudFormation comparisons
  docs/aws-professional/services.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, cloud-fundamentals/subsvc, do-not-merge

#2914 Minor punctuation fix
  docs/patterns/event-sourcing.md
Labels: Change sent to author, architecture-center/svc, design-pattern/subsvc, ready-to-merge

#2923 Update small-medium-data-warehouse-content.md
  docs/example-scenario/data/small-medium-data-warehouse-content.md
Labels: do-not-merge, review-team-triage

#2926 removing link to dev spaces for vscode
  docs/framework/devops/release-engineering-app-dev.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, do-not-merge, well-architected/subsvc

#2942 Small typo fixed
  docs/best-practices/api-implementation.md
Labels: Change sent to author, architecture-center/svc, best-practice/subsvc, do-not-merge

#2928 Update compute-decision-tree.md
  docs/guide/technology-choices/compute-decision-tree.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, guide/subsvc, ready-to-merge

#2936 Adding the response status name "No Content"
  docs/best-practices/api-design.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, best-practice/subsvc, ready-to-merge

#2950 Update index.md
  docs/aws-professional/index.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, cloud-fundamentals/subsvc, ready-to-merge

#2952 Update index.md
  docs/gcp-professional/index.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, cloud-fundamentals/subsvc, ready-to-merge

#2939 fix Azure Load Balancer scope
  docs/guide/technology-choices/load-balancing-overview.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, do-not-merge, guide/subsvc

#2948 Remove duplicate entry in regards to SQL Instance
  docs/framework/hybrid/hybrid-cost.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, do-not-merge, well-architected/subsvc

#2955 Update services.md
  docs/gcp-professional/services.md
Labels: Change sent to author, architecture-center/svc, cloud-fundamentals/subsvc, do-not-merge

#2956 Update index.md
  docs/gcp-professional/index.md
Labels: Change sent to author, architecture-center/svc, cloud-fundamentals/subsvc, do-not-merge

#2954 Update databases.md
  includes/aws/databases.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, do-not-merge

#2968 Update services.md
  docs/gcp-professional/services.md
Labels: Change sent to author, architecture-center/svc, cloud-fundamentals/subsvc, ready-to-merge

#2944 Cropped & added white background to SVG
  docs/example-scenario/data/media/small-medium-data-warehouse/small-medium-data-warehouse.svg
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, do-not-merge, example-scenario/subsvc

#2971 Resolve syncing conflicts from repo_sync_working_branch to master
  docs/patterns/_images/deployment-stamp/deployment-stamp-traffic-routing.png
  docs/patterns/_images/deployment-stamp/deployment-stamp.png
  docs/reference-architectures/dmz/secure-vnet-dmz-content.md
  docs/reference-architectures/hybrid-networking/expressroute-content.md
Labels: do-not-merge, review-team-triage

#2964 Update networking.md
  includes/aws/networking.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, do-not-merge
