Repository MicrosoftDocs/architecture-center, pull requests merged in 2021-02, with the labels that each got.

#2625 Update hub-spoke-content.md
  docs/reference-architectures/hybrid-networking/hub-spoke-content.md
Labels: do-not-merge, review-team-triage

#2624 Update hub-spoke-content.md
  docs/reference-architectures/hybrid-networking/hub-spoke-content.md
Labels: do-not-merge, review-team-triage

#2629 Update Data warehousing architecture diagram
  DataWarehousing.png
  docs/example-scenario/data/data-warehouse-content.md
Labels: do-not-merge, review-team-triage

#2538 Event Hubs is also a pub/sub system and should be added to the publish/subscribe pattern doc
  docs/patterns/publisher-subscriber.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, design-pattern/subsvc, do-not-merge

#2616 Update index.md
  docs/patterns/publisher-subscriber.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, ready-to-merge

#2626 Changes in the security Area
  docs/reference-architectures/sap/run-sap-hana-for-linux-virtual-machines-content.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, do-not-merge, review-team-triage

#2634 Fix build issues in metadata
  docs/reference-architectures/data/mdm-in-azure-with-profisee.yml
Labels: Change sent to author, architecture-center/svc, do-not-merge

#2639 Adding link to relevant blog post
  docs/guide/architecture-styles/event-driven.md
Labels: Change sent to author, architecture-center/svc, do-not-merge, guide/subsvc

#2641 Adding Next Steps
  docs/example-scenario/iot/attestation-provisioning-content.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, do-not-merge, review-team-triage

#2636 Updating with Next Steps
  docs/solution-ideas/articles/iot-controlling-devices-with-voice-assistant-content.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, do-not-merge, review-team-triage

#2643 Update hub-spoke-content.md
  docs/reference-architectures/hybrid-networking/hub-spoke-content.md
Labels: do-not-merge, review-team-triage

#2649 Added link to event-driven architecture guidance
  docs/patterns/cqrs.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, design-pattern/subsvc, do-not-merge

#2659 Updated DW Diagram image
  docs/example-scenario/data/media/DataWarehousing.png
Labels: do-not-merge, review-team-triage

#2660 PR review edits from public repo PR
  docs/solution-ideas/articles/gaming-using-cosmos-db-content.md
Labels: do-not-merge, review-team-triage

#2662 Added link to existing "queue-based load leveling" pattern
  docs/includes/microservices-intro.md
Labels: Change sent to author, architecture-center/svc, ready-to-merge

#2663 Code indentation consistency update
  docs/best-practices/api-implementation.md
Labels: Change sent to author, architecture-center/svc, best-practice/subsvc, do-not-merge

#2667 Update dashboards.md
  docs/databricks-monitoring/dashboards.md
Labels: Change sent to author, architecture-center/svc, azure-guide/subsvc, do-not-merge

#2668 Changed the architecture image to remove the space
  docs/solution-ideas/media/loan-chargeoff-prediction-with-azure-hdinsight-spark-clusters.png
Labels: do-not-merge, review-team-triage

#2648 Improve wording of opening sentence
  docs/microservices/design/interservice-communication.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, azure-guide/subsvc, do-not-merge

#2650 Added link to Priority Queue guidance for sending commands with messaging
  docs/patterns/cqrs.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, design-pattern/subsvc, do-not-merge

#2661 Adding guidance about logging with retries
  docs/patterns/retry.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, design-pattern/subsvc, do-not-merge

#2674 Anomaly Detector
  docs/solution-ideas/articles/anomaly-detector-process-content.md
  docs/solution-ideas/media/anomaly-detector.png
  docs/solution-ideas/media/anomaly-detector.svg
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, do-not-merge

#2672 Update Application Integration using Event Grids
  docs/solution-ideas/articles/application-integration-using-event-grid-content.md
  docs/solution-ideas/media/application-integration-using-event-grid.png
  docs/solution-ideas/media/application-integration-using-event-grid.svg
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, do-not-merge, review-team-triage

#2677 Demand Forecasting and Price Optimization
  docs/solution-ideas/media/demand-forecasting-and-price-optimization.png
  docs/solution-ideas/media/demand-forecasting-and-price-optimization.svg
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, do-not-merge

#2671 Added new section - Next steps
  docs/hybrid/azure-functions-hybrid-content.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, do-not-merge

#2682 Solution Idea Update - Merge for Mitha
  docs/solution-ideas/articles/digital-marketing-using-azure-database-for-mysql-content.md
  docs/solution-ideas/media/digital-marketing-using-azure-database-for-mysql..png
Labels: do-not-merge, review-team-triage
