Repository MicrosoftDocs/architecture-center, pull requests merged in 2021-06, with the labels that each got.

#2790 docs: added profisee purview docs to ref arch
  docs/reference-architectures/data/images/Purview-MicroserviceDesign-Architecture.jpg
  docs/reference-architectures/data/images/Purview-MicroserviceDesign-MatchingImage.jpg
  docs/reference-architectures/data/images/detailed-profisee-purview-integration.png
  docs/reference-architectures/data/images/example-portal-view-for-governance.png
  docs/reference-architectures/data/images/governance-summary-view.png
  docs/reference-architectures/data/images/integration-use-case.png
  docs/reference-architectures/data/images/profisee-arm-template.jpg
  docs/reference-architectures/data/images/purview-data-flow-to-profisee-portal.png
  docs/reference-architectures/data/images/purview-graphic-for-rda.png
  docs/reference-architectures/data/profisee-mdm-and-azure-purview-content.md
  docs/reference-architectures/data/profisee-mdm-and-azure-purview.yml
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, do-not-merge, reference-architecture/subsvc, review-team-triage

#2850 Fix typo in Data consistency section
  docs/framework/resiliency/design-requirements.md
Labels: Change sent to author, architecture-center/svc, do-not-merge, well-architected/subsvc

#2858 reverse public repo PR 2790 and move to private repo to fix sync PR
  docs/reference-architectures/data/images/Purview-MicroserviceDesign-Architecture.jpg
  docs/reference-architectures/data/images/Purview-MicroserviceDesign-MatchingImage.jpg
  docs/reference-architectures/data/images/detailed-profisee-purview-integration.png
  docs/reference-architectures/data/images/example-portal-view-for-governance.png
  docs/reference-architectures/data/images/governance-summary-view.png
  docs/reference-architectures/data/images/integration-use-case.png
  docs/reference-architectures/data/images/profisee-arm-template.jpg
  docs/reference-architectures/data/images/purview-data-flow-to-profisee-portal.png
  docs/reference-architectures/data/images/purview-graphic-for-rda.png
  docs/reference-architectures/data/profisee-mdm-and-azure-purview-content.md
  docs/reference-architectures/data/profisee-mdm-and-azure-purview.yml
Labels: do-not-merge, review-team-triage

#2854 fix: Always point to the latest KEDA docs
  docs/reference-architectures/containers/aks/secure-baseline-aks-content.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, do-not-merge

#2857 Update interservice-communication.md
  docs/microservices/design/interservice-communication.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, azure-guide/subsvc, do-not-merge

#2856 new name for Defender ATP
  docs/framework/security/design-admins.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, do-not-merge, well-architected/subsvc

#2861 update geode pattern document with examples and considerations
  docs/patterns/geodes.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, design-pattern/subsvc, ready-to-merge

#2894 Update manufacturing.md
  docs/industries/manufacturing.md
Labels: Change sent to author, architecture-center/svc, do-not-merge

#2865 add cosmos security, availability considerations
  docs/solution-ideas/articles/globally-distributed-mission-critical-applications-using-cosmos-db-content.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, do-not-merge, review-team-triage

#2900 Add Azure Bastion as the jumpbox recommendation
  docs/reference-architectures/n-tier/n-tier-sql-server-content.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, do-not-merge, review-team-triage

#2893 Adding section on Managed Apache Cassandra
  docs/best-practices/cassandra.md
Labels: Change sent to author, aq-pr-triaged, architecture-center/svc, best-practice/subsvc, ready-to-merge
