Repository MicrosoftDocs/architecture-center, pull requests merged in 2022-04, with the labels that each got.

#3369 Update run-sap-bw4hana-with-linux-virtual-machines-content.md
  docs/reference-architectures/sap/run-sap-bw4hana-with-linux-virtual-machines-content.md
Labels: do-not-merge, aq-pr-triaged, review-team-triage

#3379 Move up instance IP note
  docs/example-scenario/gateway/firewall-application-gateway-content.md
Labels: do-not-merge, aq-pr-triaged, review-team-triage

#3386 Typo "Postgres Hyperscale"→"PostgreSQL Hyperscale"
  docs/guide/multitenant/approaches/storage-data-content.md
Labels: do-not-merge, aq-pr-triaged, review-team-triage

#3391 Adding LinkedIn link.
  docs/operator-guides/aks/troubleshoot-network-aks.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, aq-pr-triaged, azure-guide/subsvc

#3381 Update firewall-application-gateway-content.md
  docs/example-scenario/gateway/firewall-application-gateway-content.md
Labels: do-not-merge, aq-pr-triaged, review-team-triage

#3398 Retry guidance: Rewording Cosmos DB retry guidance
  docs/best-practices/retry-service-specific.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, aq-pr-triaged, best-practice/subsvc
