Repository MicrosoftDocs/architecture-center, pull requests merged in 2022-09, with the labels that each got.

#3625 Clarify SAProuter tunnel architecture
  docs/guide/sap/sap-internet-inbound-outbound-content.md
Labels: do-not-merge, review-team-triage

#3620 Azure Archicture Center contribution
  docs/hybrid/azure-arc-hybrid-config-content.md
Labels: do-not-merge, aq-pr-triaged, review-team-triage

#3619 Add Ably as an alternative
  docs/example-scenario/signalr/index-content.md
Labels: do-not-merge, aq-pr-triaged, review-team-triage

#3616 add the missing link for network policies
  docs/reference-architectures/containers/aks/baseline-aks-content.md
Labels: do-not-merge, aq-pr-triaged, review-team-triage

#3605 AFS update
  docs/solution-ideas/articles/backup-archive-on-premises-content.md
Labels: do-not-merge, aq-pr-triaged, review-team-triage

#3627 Adding additional related resources links
  docs/example-scenario/apps/devops-dotnet-webapp-content.md
Labels: do-not-merge, aq-pr-triaged, review-team-triage, qualifies-for-auto-merge

#3631 Typo "GitHub action workflow"→"GitHub Action workflow"
  docs/reference-architectures/containers/aks-multi-region/aks-multi-cluster-content.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, aq-pr-triaged, qualifies-for-auto-merge

#3630 Update reference-architecture-for-oracle-database-migration-to-azure-…
  docs/solution-ideas/articles/reference-architecture-for-oracle-database-migration-to-azure-content.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, aq-pr-triaged, review-team-triage, qualifies-for-auto-merge

#3639 Added component links
  docs/hybrid/azure-network-adapter-content.md
Labels: do-not-merge, aq-pr-triaged, review-team-triage, qualifies-for-auto-merge

#3629 Typo "Azure blob"→"Azure Blob"
  docs/data-science-process/data-blob.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, aq-pr-triaged, azure-guide/subsvc, qualifies-for-auto-merge

#3644 PowerShell script correction
  docs/networking/prefixes/add-ip-space-peered-vnet-content.md
Labels: do-not-merge, aq-pr-triaged, review-team-triage, needs-human-review

#3640 Added component links
  docs/hybrid/hybrid-dns-infra-content.md
Labels: do-not-merge, aq-pr-triaged, review-team-triage, qualifies-for-auto-merge

#3637 Update hub-spoke-content.md
  docs/reference-architectures/hybrid-networking/hub-spoke-content.md
Labels: do-not-merge, aq-pr-triaged, review-team-triage, qualifies-for-auto-merge

#3646 Create a variable in the script for the share name
  docs/example-scenario/wvd/windows-virtual-desktop-fslogix-content.md
Labels: do-not-merge, aq-pr-triaged, review-team-triage, qualifies-for-auto-merge

#3651 Update migrate-master-data-services-with-cluedin-content.md
  docs/reference-architectures/data/migrate-master-data-services-with-cluedin-content.md
Labels: do-not-merge, review-team-triage, qualifies-for-auto-merge

#3649 Typo "Azure files"→"Azure Files"
  docs/example-scenario/hybrid/azure-files-on-premises-authentication.yml
Labels: Change sent to author, ready-to-merge, architecture-center/svc, aq-pr-triaged, needs-human-review

#3609 Added description of failure scenarios when code uses databases and brokers together
  docs/reference-architectures/containers/aks-mission-critical/mission-critical-data-platform.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, reference-architecture/subsvc, aq-pr-triaged

#3658 Update iot-content.md
  docs/reference-architectures/iot-content.md
Labels: do-not-merge, aq-pr-triaged, review-team-triage, qualifies-for-auto-merge

#3673 Typo "Azure table"→"Azure Table"
  docs/best-practices/data-partitioning-strategies-content.md
Labels: do-not-merge, review-team-triage, qualifies-for-auto-merge

#3671 Add link to Azure REST API Guidelines
  docs/best-practices/api-design.md
Labels: Change sent to author, ready-to-merge, architecture-center/svc, aq-pr-triaged, best-practice/subsvc, qualifies-for-auto-merge

#3676 Update digital-media-video-content.md
  docs/solution-ideas/articles/digital-media-video-content.md
  docs/solution-ideas/articles/digital-media-video.yml
Labels: do-not-merge, aq-pr-triaged, review-team-triage, needs-human-review
