Repository MicrosoftDocs/architecture-center, pull requests merged in 2022-12, with the labels that each got.

#3789 Updated files as per issue #3786
  docs/example-scenario/teams/media/securing-bot-image-009.png
  docs/example-scenario/teams/media/securing-bot-image-010.png
  docs/example-scenario/teams/media/securing-bot-image-011.png
Labels: do-not-merge, aq-pr-triaged, review-team-triage, needs-human-review

#3816 [ContainersARB] Refresh CI/CD for microservices architectures
  docs/microservices/ci-cd-content.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, aq-pr-triaged, qualifies-for-auto-merge

#3819 Update product name in aks-baseline-content.md
  docs/example-scenario/hybrid/aks-baseline-content.md
Labels: do-not-merge, review-team-triage, qualifies-for-auto-merge

#3821 Update iot-architecture-overview.md
  docs/reference-architectures/iot/iot-architecture-overview.md
Labels: Change sent to author, ready-to-merge, architecture-center/svc, reference-architecture/subsvc, aq-pr-triaged, needs-human-review

#3820 Update hybrid-identity-content.md
  docs/solution-ideas/articles/hybrid-identity-content.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, aq-pr-triaged, qualifies-for-auto-merge

#3837 Fix simple typos
  docs/patterns/event-sourcing-content.md
Labels: do-not-merge, review-team-triage, qualifies-for-auto-merge
