Repository MicrosoftDocs/architecture-center, pull requests merged in 2022-08, with the labels that each got.

#3570 Adjusted for better 'Readabilty'
  docs/guide/responsible-innovation/index.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, guide/subsvc

#3568 Typo "Azure file storage"→"Azure File Storage"
  docs/example-scenario/file-storage/moodle-azure-netapp-files-content.md
Labels: do-not-merge, aq-pr-triaged, review-team-triage

#3587 Update well-architected-framework-azure-firewall.md
  docs/networking/guide/well-architected-framework-azure-firewall.md
Labels: Change sent to author, ready-to-merge, architecture-center/svc, aq-pr-triaged, azure-guide/subsvc

#3594 improve the readability with and/or instead of and, or
  docs/reference-architectures/containers/aks/secure-baseline-aks-content.md
Labels: do-not-merge

#3577 Update analytical-data-stores.md
  docs/data-guide/technology-choices/analytical-data-stores.md
Labels: Change sent to author, ready-to-merge, architecture-center/svc, aq-pr-triaged, azure-guide/subsvc

#3571 Adjusted for better 'readability'.
  docs/patterns/index.md
Labels: Change sent to author, ready-to-merge, architecture-center/svc, aq-pr-triaged, design-pattern/subsvc

#3569 Adjusted wording for better readability.
  docs/guide/index.md
Labels: Change sent to author, ready-to-merge, architecture-center/svc, aq-pr-triaged, guide/subsvc

#3556 Multiple VWAN Hubs in same region is available
  docs/networking/hub-spoke-vwan-architecture-content.md
Labels: do-not-merge, aq-pr-triaged, review-team-triage

#3558 Update well-architected-network-address-translation-gateway-content.md
  docs/networking/guide/well-architected-network-address-translation-gateway-content.md
Labels: do-not-merge, aq-pr-triaged, review-team-triage

#3561 Corrected LinkedIn Profile URL
  docs/example-scenario/data/open-source-data-engine-stream-processing-content.md
Labels: do-not-merge, aq-pr-triaged, review-team-triage

#3573 Adjusted for better 'readability'.
  docs/reference-architectures/containers/aks-mission-critical/mission-critical-intro-content.md
Labels: do-not-merge, aq-pr-triaged, review-team-triage

#3586 added mention of Standard network features
  docs/example-scenario/wvd/windows-virtual-desktop-fslogix-content.md
Labels: do-not-merge, aq-pr-triaged, review-team-triage

#3595 Update azure-nifi-content.md
  docs/example-scenario/data/azure-nifi-content.md
Labels: do-not-merge, aq-pr-triaged, review-team-triage

#3555 correct k3s link
  docs/operator-guides/aks/choose-bare-metal-kubernetes-content.md
Labels: do-not-merge, aq-pr-triaged, review-team-triage

#3547 Add Azure Red Hat OpenShift content into decision tree
  docs/guide/technology-choices/compute-decision-tree-content.md
Labels: do-not-merge, aq-pr-triaged, review-team-triage

#3600 Use AuthenticationSchemes instead
  docs/multitenant-identity/web-api-content.md
Labels: do-not-merge, aq-pr-triaged, review-team-triage
