Repository MicrosoftDocs/architecture-center, pull requests merged in 2022-10, with the labels that each got.

#3682 Typo "Azure files"→"Azure Files"
  docs/example-scenario/wvd/windows-virtual-desktop-fslogix-content.md
Labels: do-not-merge, review-team-triage, qualifies-for-auto-merge

#3681 Update to CI/CD for Azure Web Apps
  docs/solution-ideas/articles/azure-devops-continuous-integration-and-continuous-deployment-for-azure-web-apps-content.md
  docs/solution-ideas/articles/azure-devops-continuous-integration-and-continuous-deployment-for-azure-web-apps.yml
  docs/solution-ideas/media/azure-devops-cicd-for-azure-web-apps.png
Labels: Change sent to author, ready-to-merge, aq-pr-triaged, review-team-triage, needs-human-review

#3688 Cross-linking between patterns
  docs/patterns/retry-content.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, aq-pr-triaged, review-team-triage, qualifies-for-auto-merge

#3690 Linking to libraries which implement the design consideration
  docs/best-practices/auto-scaling.md
Labels: Change sent to author, ready-to-merge, architecture-center/svc, aq-pr-triaged, best-practice/subsvc, qualifies-for-auto-merge

#3689 Cross-linking to auto-scaling
  docs/patterns/throttling-content.md
Labels: Change sent to author, ready-to-merge, architecture-center/svc, aq-pr-triaged, qualifies-for-auto-merge

#3697 Describe 'Critical Time' as an attribute useful for auto-scaling decisions
  docs/best-practices/auto-scaling.md
Labels: Change sent to author, ready-to-merge, architecture-center/svc, best-practice/subsvc, qualifies-for-auto-merge

#3684 Update saas-digital-business-journey-azure.md
  docs/guide/saas/saas-digital-business-journey-azure.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, aq-pr-triaged, azure-guide/subsvc, needs-human-review

#3705 Cross linking to circuit breaker pattern
  docs/includes/microservices-intro.md
Labels: Change sent to author, ready-to-merge, architecture-center/svc, aq-pr-triaged, guide/subsvc, qualifies-for-auto-merge

#3706 Enriching the guidance for APIs needing asynchronous support for long-running requests
  docs/best-practices/api-implementation.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, aq-pr-triaged, best-practice/subsvc, qualifies-for-auto-merge

#3704 Additional detail about health checks when using message brokers
  docs/reference-architectures/containers/aks-mission-critical/mission-critical-data-platform.md
Labels: Change sent to author, ready-to-merge, architecture-center/svc, reference-architecture/subsvc, aq-pr-triaged, qualifies-for-auto-merge

#3702 Update aks-upgrade-practices.md
  docs/operator-guides/aks/aks-upgrade-practices.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, reference-architecture/subsvc, aq-pr-triaged, qualifies-for-auto-merge

#3703 Update small-medium-data-warehouse-content.md
  docs/example-scenario/data/small-medium-data-warehouse-content.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, example-scenario/subsvc, aq-pr-triaged, review-team-triage, qualifies-for-auto-merge

#3709 Fix malformed links in DevOps section
  docs/reference-architectures/containers/aks-microservices/aks-microservices-content.md
Labels: do-not-merge, qualifies-for-auto-merge

#3716 Cross-linking to relevant guidance
  docs/includes/microservices-intro.md
Labels: Change sent to author, ready-to-merge, architecture-center/svc, aq-pr-triaged, guide/subsvc, qualifies-for-auto-merge

#3711 Cross-linking to the implementation guidelines
  docs/best-practices/api-design.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, aq-pr-triaged, best-practice/subsvc, qualifies-for-auto-merge

#3720 Update enterprise-grade-logging-content.md
  docs/reference-architectures/logging/enterprise-grade-logging-content.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, aq-pr-triaged, review-team-triage, qualifies-for-auto-merge

#3712 Cross-linking to relevant guidelines
  docs/best-practices/background-jobs.md
Labels: Change sent to author, ready-to-merge, architecture-center/svc, aq-pr-triaged, best-practice/subsvc, qualifies-for-auto-merge

#3718 Cross linking to authoritative guidance
  docs/microservices/migrate-monolith-content.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, aq-pr-triaged, qualifies-for-auto-merge

#3717 Define SRE acronym
  docs/reference-architectures/containers/aks-pci/aks-pci-ra-code-assets-content.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, reference-architecture/subsvc, aq-pr-triaged, review-team-triage, qualifies-for-auto-merge

#3736 Update messaging.md
  docs/aws-professional/messaging.md
Labels: Change sent to author, ready-to-merge, architecture-center/svc, cloud-fundamentals/subsvc, aq-pr-triaged, qualifies-for-auto-merge

#3738 Updating ownership
  docs/guide/mobile/azure-communication-services-architecture.yml
Labels: Change sent to author, do-not-merge, architecture-center/svc, aq-pr-triaged, needs-human-review

#3724 Linking to technologies implementing lease management
  docs/patterns/rate-limiting-pattern-content.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, aq-pr-triaged, review-team-triage, azure-guide/subsvc, qualifies-for-auto-merge

#3723 Cross-linking to auto-scaling guidance
  docs/patterns/queue-based-load-leveling-content.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, aq-pr-triaged, azure-guide/subsvc, qualifies-for-auto-merge
