Repository MicrosoftDocs/architecture-center, pull requests merged in 2022-06, with the labels that each got.

#3448 chore: Set permissions for GitHub actions
  .github/workflows/stale.yml
Labels: Change sent to author, do-not-merge, aq-pr-triaged

#3458 Minor typo
  docs/reference-architectures/hybrid-networking/hub-spoke-content.md
Labels: do-not-merge, aq-pr-triaged, review-team-triage

#3477 Update run-sap-bw4hana-with-linux-virtual-machines.yml
  docs/reference-architectures/sap/run-sap-bw4hana-with-linux-virtual-machines.yml
Labels: Change sent to author, do-not-merge, architecture-center/svc

#3488 Update windows-virtual-desktop-content.md
  docs/example-scenario/wvd/windows-virtual-desktop-content.md
Labels: do-not-merge, aq-pr-triaged, review-team-triage

#3497 Updated Azure Container Apps status to GA
  docs/example-scenario/serverless/microservices-with-container-apps-dapr-content.md
Labels: Change sent to author, do-not-merge, aq-pr-triaged, review-team-triage

#3502 Update index-content.md to close issue 3501
  docs/reference-architectures/hybrid-networking/index-content.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, aq-pr-triaged

#3494 Typo "Azure Pipeline"→” Azure Pipelines”
  docs/serverless/guide/serverless-app-cicd-best-practices-content.md
Labels: do-not-merge, aq-pr-triaged, review-team-triage

#3493 Added documentation link for #3191
  docs/reference-architectures/hybrid-networking/hub-spoke-content.md
Labels: Change sent to author, do-not-merge, aq-pr-triaged

#3485 NDVALPHA-UPDATED-FSLOGIX-PROFILEMGMT-AND-ADCONNECT
  docs/example-scenario/wvd/azure-virtual-desktop-multi-region-bcdr-content.md
Labels: do-not-merge, aq-pr-triaged, review-team-triage
