Repository MicrosoftDocs/architecture-center, pull requests merged in 2022-05, with the labels that each got.

#3406 Update Private Connectivity to PaaS
  docs/gcp-professional/services.md
Labels: Change sent to author, ready-to-merge, architecture-center/svc, cloud-fundamentals/subsvc, aq-pr-triaged

#3399 Align HTTP status code in description to diagram
  docs/patterns/async-request-reply-content.md
Labels: do-not-merge, aq-pr-triaged, review-team-triage

#3400 Add link to Azure Sphere docs
  docs/reference-architectures/iot-content.md
Labels: do-not-merge, aq-pr-triaged, review-team-triage

#3403 Fix az command in securing-bot-teams-channel-content.md
  docs/example-scenario/teams/securing-bot-teams-channel-content.md
Labels: do-not-merge, aq-pr-triaged, review-team-triage

#3419 Typo, HIPPA->HIPAA
  docs/example-scenario/digital-health/health-portal-content.md
  docs/serverless-quest/reference-architectures.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, review-team-triage, azure-guide/subsvc

#3385 Removing the parallel R sample repo
  docs/topics/high-performance-computing.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, reference-architecture/subsvc, aq-pr-triaged

#3436 Updated doc to include Synapse for integration
  docs/mainframe/mainframe-midrange-architecture.md
Labels: Change sent to author, ready-to-merge, architecture-center/svc, reference-architecture/subsvc

#3427 Update cloud-scale-analytics-with-discovery-hub.yml
  docs/solution-ideas/articles/cloud-scale-analytics-with-discovery-hub.yml
Labels: Change sent to author, ready-to-merge, architecture-center/svc, aq-pr-triaged

#3432 Updated sync-mainframe-data-with-azure-content.md with Azure Synapse…
  docs/reference-architectures/migration/sync-mainframe-data-with-azure-content.md
Labels: do-not-merge, aq-pr-triaged, review-team-triage

#3453 613141- Article clean-up for thhickle: Azure AD join for Azure Virtual Desktop
  docs/example-scenario/wvd/azure-virtual-desktop-azure-active-directory-join.md
Labels: Change sent to author, ready-to-merge, architecture-center/svc, aq-pr-triaged, azure-guide/subsvc

#3457 Updated three to four subnets
  docs/reference-architectures/containers/aks/secure-baseline-aks-content.md
Labels: do-not-merge, aq-pr-triaged, review-team-triage
