Repository MicrosoftDocs/architecture-center, pull requests merged in 2022-03, with the labels that each got.

#3329 Update business-central-content.md
  docs/solution-ideas/articles/business-central-content.md
Labels: do-not-merge, review-team-triage

#3336 Update automate-sentinel-integration-content.md
  docs/example-scenario/devops/automate-sentinel-integration-content.md
Labels: do-not-merge, review-team-triage

#3340 Update typo/word choice in resilient-design.md
  docs/serverless/event-hubs-functions/resilient-design.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, azure-guide/subsvc

#3342 The main language of Stream Analytics is SQL
  docs/data-guide/technology-choices/stream-processing.md
Labels: Change sent to author, ready-to-merge, architecture-center/svc, aq-pr-triaged, azure-guide/subsvc

#3347 adding product tag for Azure Virtual Desktop
  docs/example-scenario/wvd/windows-virtual-desktop.yml
Labels: Change sent to author, do-not-merge, architecture-center/svc

#3363 Update adds-extend-domain-content.md
  docs/reference-architectures/identity/adds-extend-domain-content.md
Labels: do-not-merge, review-team-triage

#3373 Update Next Step resource name
  docs/example-scenario/wvd/windows-virtual-desktop-content.md
Labels: do-not-merge, review-team-triage
