Repository MicrosoftDocs/architecture-center, pull requests merged in 2022-07, with the labels that each got.

#3519 Update azure-virtual-desktop-azure-active-directory-join.md
  docs/example-scenario/wvd/azure-virtual-desktop-azure-active-directory-join.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, azure-guide/subsvc

#3529 improve an English sentence
  docs/reference-architectures/containers/aks/secure-baseline-aks-content.md
Labels: do-not-merge, review-team-triage

#3532 Typo "GitHub Action workflows"→"GitHub Actions workflows"
  docs/example-scenario/blue-green-spring/blue-green-spring-content.md
Labels: do-not-merge, review-team-triage

#3534 Fix issue #3507 - Alternatives section is confusing + Author correction
  docs/example-scenario/data/data-analysis-regulated-industries-content.md
Labels: do-not-merge, aq-pr-triaged, review-team-triage

#3531 Updated Cost Management Section
  docs/networking/guide/well-architected-framework-azure-firewall.md
Labels: Change sent to author, ready-to-merge, architecture-center/svc, aq-pr-triaged, azure-guide/subsvc

#3540 Fix typo in `mlops-maturity-model-content.md`
  docs/example-scenario/mlops/mlops-maturity-model-content.md
Labels: do-not-merge, aq-pr-triaged, review-team-triage

#3543 Update azure-digital-twins-builder-content.md
  docs/solution-ideas/articles/azure-digital-twins-builder-content.md
Labels: do-not-merge, review-team-triage

#3545 Update well-architected-framework-azure-firewall.md
  docs/networking/guide/well-architected-framework-azure-firewall.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, aq-pr-triaged, azure-guide/subsvc
