Repository MicrosoftDocs/architecture-center, pull requests merged in 2023-06, with the labels that each got.

#4067 Spelling correction of Anonymized
  docs/example-scenario/digital-health/predict-patient-length-of-stay-content.md
Labels: do-not-merge, review-team-triage, qualifies-for-auto-merge

#4076 Add text: "New Relic" integration with Azure Monitor (link)
  docs/reference-architectures/app-service-web-app/app-monitoring-content.md
Labels: do-not-merge, aq-pr-triaged, review-team-triage, qualifies-for-auto-merge

#4056 UPDATE: Added Enterprise-scale landing zone for Citrix on Azure
  docs/landing-zones/landing-zone-deploy.md
Labels: Change sent to author, ready-to-merge, architecture-center/svc, aq-pr-triaged, guide/subsvc, qualifies-for-auto-merge

#4074 Update Doc: Include New Relic as one of the third-party solution.
  docs/reference-architectures/containers/aks/baseline-aks-content.md
Labels: Change sent to author, ready-to-merge, aq-pr-triaged, qualifies-for-auto-merge

#4099 Update - Removed github logo in line with content
  docs/patterns/health-endpoint-monitoring-content.md
Labels: ready-to-merge, aq-pr-triaged, review-team-triage, qualifies-for-auto-merge, pending-content-team/business-approval

#4104 Removing References to Syncier Security Tower from Documentation as it is EOL
  docs/example-scenario/gitops-aks/gitops-blueprint-aks-content.md
Labels: ready-to-merge, aq-pr-triaged, qualifies-for-auto-merge

#4105 Update baseline-zone-redundant-content.md - Increase readabiility an…
  docs/reference-architectures/app-service-web-app/baseline-zone-redundant-content.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, aq-pr-triaged, qualifies-for-auto-merge

#4134 Update aks-cicd-azure-pipelines-content.md - Increase readability
  docs/guide/aks/aks-cicd-azure-pipelines-content.md
Labels: do-not-merge, review-team-triage, qualifies-for-auto-merge

#4133 Update index.md - Increase readability
  docs/guide/azure-resource-manager/advanced-templates/index.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, azure-guide/subsvc, needs-human-review
