Repository MicrosoftDocs/architecture-center, pull requests merged in 2023-01, with the labels that each got.

#3838 Update geospatial-processing-analytics.yml
  docs/industries/aerospace/geospatial-processing-analytics.yml
Labels: Change sent to author, do-not-merge, architecture-center/svc, needs-human-review

#3834 Linking to libraries that support the pattern
  docs/best-practices/transactional-outbox-cosmos-content.md
Labels: do-not-merge, aq-pr-triaged, review-team-triage, qualifies-for-auto-merge

#3842 Update enterprise-grade-logging-content.md
  docs/reference-architectures/logging/enterprise-grade-logging-content.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, qualifies-for-auto-merge

#3868 Update EventHub Trigger Batch settings
  docs/serverless/event-hubs-functions/performance-scale-content.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, qualifies-for-auto-merge

#3828 Update stream-processing.md
  docs/data-guide/technology-choices/stream-processing.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, aq-pr-triaged, azure-guide/subsvc, qualifies-for-auto-merge

#3875 External configuration for limits/policies.Additional considerations
  docs/patterns/throttling-content.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, aq-pr-triaged, qualifies-for-auto-merge
