Repository MicrosoftDocs/architecture-center, pull requests merged in 2023-03, with the labels that each got.

#3936 Typo "PostgresSQL"→"PostgreSQL"
  docs/guide/multitenant/service/postgresql.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, azure-guide/subsvc, qualifies-for-auto-merge

#3937 Another option for throttling
  docs/patterns/throttling-content.md
Labels: do-not-merge, aq-pr-triaged, review-team-triage, qualifies-for-auto-merge

#3945 Typo "Azure DB for MySQL"→"Azure Database for MySQL"
  docs/solution-ideas/articles/scalable-web-and-mobile-applications-using-azure-database-for-mysql.yml
Labels: Change sent to author, do-not-merge, architecture-center/svc, aq-pr-triaged, needs-human-review

#3946 Typo "Azure DB for PostgreSQL"→"Azure Database for PostgreSQL"
  docs/solution-ideas/articles/scalable-web-and-mobile-applications-using-azure-database-for-postgresql.yml
Labels: Change sent to author, do-not-merge, architecture-center/svc, aq-pr-triaged, needs-human-review

#3947 Update aks-pci-monitor-content.md to remove File Integrity Monitoring from Defender for Containers
  docs/reference-architectures/containers/aks-pci/aks-pci-monitor-content.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, aq-pr-triaged, qualifies-for-auto-merge

#3950 Update step 6 under Dataflow
  docs/example-scenario/security/hardened-web-app-content.md
Labels: ready-to-merge, aq-pr-triaged, review-team-triage, qualifies-for-auto-merge

#3959 Typo "Azure DB for MySQL"→"Azure Database for MySQL"
  docs/solution-ideas/articles/finance-management-apps-using-azure-database-for-mysql.yml
Labels: Change sent to author, do-not-merge, architecture-center/svc, needs-human-review

#3957 Corrected vnet to VNet
  docs/reference-architectures/sap/run-sap-hana-for-linux-virtual-machines-content.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, aq-pr-triaged, qualifies-for-auto-merge

#3932 Update - Added Web link to page
  docs/data-guide/disaster-recovery/dr-for-azure-data-platform-architecture-content.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, aq-pr-triaged, review-team-triage, azure-guide/subsvc, qualifies-for-auto-merge

#3943 Update: change ACI with ACA when comparing to Cloud Run
  docs/gcp-professional/services.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, cloud-fundamentals/subsvc, aq-pr-triaged, qualifies-for-auto-merge, pending-content-team/business-approval

#3966 Update migrate-monolith.yml
  docs/microservices/migrate-monolith.yml
Labels: Change sent to author, do-not-merge, architecture-center/svc, needs-human-review

#3967 Corrected spelling of continuous
  docs/example-scenario/banking/banking-system-cloud-transformation-content.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, qualifies-for-auto-merge

#3972 Update api-design.md
  docs/best-practices/api-design.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, best-practice/subsvc, qualifies-for-auto-merge

#3975 Minor update: Updated Raincode Refactor to Rehost. Raincode is a Rehost solution. Updated link: https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/app-modernization/raincode-reference-architecture. In this link the heading Refactor should be changed to Rehost.
  docs/example-scenario/mainframe/general-mainframe-refactor-content.md
  docs/example-scenario/mainframe/refactor-mainframe-applications-advanced-content.md
  docs/example-scenario/mainframe/refactor-mainframe-applications-astadia-content.md
  docs/guide/partner-scenarios.md
  docs/integration/integration-start-here-content.md
  docs/mainframe/mainframe-midrange-architecture.md
  docs/reference-architectures/app-modernization/raincode-reference-architecture.yml
  includes/cards/raincode-reference-architecture-card.md
Labels: ready-to-merge, aq-pr-triaged, review-team-triage, pending-content-team/business-approval

#3976 Fixed typo of Traininging
  docs/example-scenario/dataplate2e/data-platform-end-to-end-content.md
Labels: do-not-merge, review-team-triage, qualifies-for-auto-merge

#3952 Correction of VNets from VNETS
  docs/reference-architectures/sap/hana-large-instances-content.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, aq-pr-triaged, qualifies-for-auto-merge

#3968 Update link to HPC landing zone in landing-zone-deploy.md
  docs/landing-zones/landing-zone-deploy.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, aq-pr-triaged, guide/subsvc, qualifies-for-auto-merge
