Repository MicrosoftDocs/architecture-center, pull requests merged in 2023-02, with the labels that each got.

#3884 Update to cross-link to the problems this article is solving
  docs/best-practices/transactional-outbox-cosmos-content.md
Labels: do-not-merge, aq-pr-triaged, review-team-triage, qualifies-for-auto-merge

#3892 Update spot-eviction-content.md
  docs/guide/spot/spot-eviction-content.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, aq-pr-triaged, qualifies-for-auto-merge

#3899 Link to library which supports the pattern
  docs/patterns/claim-check-content.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, aq-pr-triaged, review-team-triage

#3922 Add link to hybrid DNS architecture
  docs/hybrid/hybrid-dns-infra-content.md
Labels: do-not-merge, aq-pr-triaged, review-team-triage, qualifies-for-auto-merge

#3929 Link to definition & cross-linking
  docs/reliability/architect.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, well-architected/subsvc, qualifies-for-auto-merge

#3928 Additional guidance on handling retries
  docs/patterns/scheduler-agent-supervisor-content.md
Labels: do-not-merge, review-team-triage, qualifies-for-auto-merge
