Repository MicrosoftDocs/architecture-center, pull requests merged in 2023-04, with the labels that each got.

#3986 Spelling correction of Cost-effictive
  docs/solution-ideas/articles/dev-test-iaas-content.md
Labels: do-not-merge, review-team-triage, qualifies-for-auto-merge

#3955 [ContainersARB] Refresh - Deploy microservices with Azure Container Apps
  docs/example-scenario/serverless/microservices-with-container-apps-content.md
Labels: Change sent to author, ready-to-merge, architecture-center/svc, aq-pr-triaged, qualifies-for-auto-merge

#3992 Typo "PostgresSQL"→"PostgreSQL"
  docs/reference-architectures/ibm/deploy-ibm-sterling-oms-content.md
Labels: do-not-merge, review-team-triage, qualifies-for-auto-merge

#3999 fix: data-lake-store retry-service-specific.md whitespace/text
  docs/best-practices/retry-service-specific.md
Labels: Change sent to author, ready-to-merge, architecture-center/svc, aq-pr-triaged, best-practice/subsvc, qualifies-for-auto-merge, pending-content-team/business-approval

#4000 Typo "PostgresSQL"→"PostgreSQL"
  docs/hybrid/azure-stack-robo-content.md
Labels: do-not-merge, qualifies-for-auto-merge

#4016 Update landing-zone-deploy.md
  docs/landing-zones/landing-zone-deploy.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, aq-pr-triaged, guide/subsvc, qualifies-for-auto-merge
