Repository MicrosoftDocs/architecture-center, pull requests merged in 2024-06, with the labels that each got.

#4447 Informing readers about a prevalent issue
  docs/reference-architectures/saga/saga-content.md
Labels: ready-to-merge, review-team-triage, qualifies-for-auto-merge

#4448 Informing readers about a prevalent issue
  docs/patterns/compensating-transaction-content.md
Labels: ready-to-merge, review-team-triage, qualifies-for-auto-merge

#4424 Update - persistent and non-persistent terminology clarity
  docs/example-scenario/azure-virtual-desktop/azure-virtual-desktop-content.md
Labels: ready-to-merge, architecture-center/svc, example-scenario/subsvc, aq-pr-triaged, qualifies-for-auto-merge

#4449 Update scheduler-agent-supervisor-content.md
  docs/patterns/scheduler-agent-supervisor-content.md
Labels: ready-to-merge, review-team-triage, qualifies-for-auto-merge

#4450 Update choreography-content.md
  docs/patterns/choreography-content.md
Labels: do-not-merge, review-team-triage, qualifies-for-auto-merge

#4452 Update interservice-communication-content.md
  docs/microservices/design/interservice-communication-content.md
Labels: ready-to-merge, review-team-triage, qualifies-for-auto-merge

#4455 Informing readers about fallacies of distributed computing
  docs/patterns/category/design-implementation.md
Labels: Change sent to author, do-not-merge, architecture-center/svc, aq-pr-triaged, design-pattern/subsvc, qualifies-for-auto-merge

#4457 Number of nodes getting upgraded simultaneously also depend on surge …
  docs/operator-guides/aks/aks-upgrade-practices.md
Labels: Change sent to author, ready-to-merge, architecture-center/svc, reference-architecture/subsvc, aq-pr-triaged, qualifies-for-auto-merge

#4467 Update choreography-content.md
  docs/patterns/choreography-content.md
Labels: Change sent to author, ready-to-merge, architecture-center/svc, aq-pr-triaged, qualifies-for-auto-merge

#4465 Update n-tier-content.md
  docs/guide/architecture-styles/n-tier-content.md
Labels: ready-to-merge, aq-pr-triaged, qualifies-for-auto-merge, pending-content-team/business-approval

#4464 Update tactical-ddd-content.md
  docs/microservices/model/tactical-ddd-content.md
Labels: ready-to-merge, aq-pr-triaged, qualifies-for-auto-merge, pending-content-team/business-approval

#4466 Update index.md
  docs/guide/architecture-styles/index.md
Labels: Change sent to author, ready-to-merge, architecture-center/svc, aq-pr-triaged, guide/subsvc, needs-human-review, pending-content-team/business-approval

#4471 Fix a few typos
  docs/ai-ml/guide/azure-openai-gateway-multi-backend-content.md
  docs/ai-ml/guide/conversation-summarization-content.md
  docs/ai-ml/index.md
  docs/best-practices/data-partitioning-content.md
  docs/example-scenario/ai/real-time-anomaly-detection-conveyor-belt-content.md
  docs/example-scenario/analytics/sync-mongodb-atlas-azure-synapse-analytics-content.md
  docs/example-scenario/data/realtime-analytics-vehicle-iot-content.md
  docs/example-scenario/iot/application-stamps-content.md
  docs/example-scenario/iot/efficient-docker-image-deployment-content.md
  docs/example-scenario/magento/magento-azure-content.md
  docs/example-scenario/monitoring/enterprise-monitoring-content.md
  docs/example-scenario/serverless/microservices-with-container-apps-content.md
  docs/guide/iot-edge-vision/camera.md
  docs/hybrid/azure-stack-vm-disaster-recovery-content.md
  docs/patterns/async-request-reply-content.md
  docs/patterns/choreography-content.md
  docs/reference-architectures/containers/aks-microservices/aks-microservices-content.md
  docs/reference-architectures/containers/aks-mission-critical/mission-critical-data-platform.md
  docs/reference-architectures/containers/aks-mission-critical/mission-critical-health-modeling.md
  docs/reference-architectures/containers/aks-multi-region/aks-multi-cluster-content.md
  docs/reference-architectures/containers/aks/baseline-aks-content.md
  docs/reference-architectures/event-hubs/partitioning-in-event-hubs-and-kafka-content.md
  docs/reference-architectures/media-services/gridwich-storage-service-content.md
  docs/solution-ideas/articles/azure-vmware-solution-foundation-landing-zone-content.md
  docs/virtual-machines/baseline-content.md
Labels: ready-to-merge, review-team-triage, needs-human-review

#4469 Update web-app-content.md
  docs/web-apps/serverless/architectures/web-app-content.md
Labels: do-not-merge, aq-pr-triaged, qualifies-for-auto-merge, pending-content-team/business-approval

#4474 Update non-relational-data-content.md
  docs/data-guide/big-data/non-relational-data-content.md
Labels: ready-to-merge, aq-pr-triaged, qualifies-for-auto-merge, pending-content-team/business-approval

#4446 Update IoT services
  docs/gcp-professional/services.md
Labels: Change sent to author, ready-to-merge, architecture-center/svc, cloud-fundamentals/subsvc, aq-pr-triaged, qualifies-for-auto-merge, pending-content-team/business-approval

#4475 Update pipes-and-filters-content.md
  docs/patterns/pipes-and-filters-content.md
Labels: ready-to-merge, aq-pr-triaged, qualifies-for-auto-merge

#4476 Update run-sap-bw4hana-with-linux-virtual-machines-content.md broken link
  docs/reference-architectures/sap/run-sap-bw4hana-with-linux-virtual-machines-content.md
Labels: Change sent to author, ready-to-merge, aq-pr-triaged, qualifies-for-auto-merge

#4479 [UPDATE] Updating supported-automation-capabilities image for adding terraform support for watchlist and automation rules
  docs/example-scenario/devops/media/supported-automation-capabilities.png
Labels: ready-to-merge, aq-pr-triaged, review-team-triage, needs-human-review, pending-content-team/business-approval

#4483 Add Azure Application Gateway to table
  docs/networking/guide/ipv6-ip-planning.md
Labels: Change sent to author, ready-to-merge, architecture-center/svc, azure-guide/subsvc, qualifies-for-auto-merge
