Repository MicrosoftDocs/architecture-center, pull requests merged in 2024-01, with the labels that each got.

#4345 Fix a few typos
  docs/ai-ml/architecture/automate-document-processing-azure-form-recognizer-content.md
  docs/antipatterns/synchronous-io/index.md
  docs/data-guide/disaster-recovery/dr-for-azure-data-platform-recommendations-content.md
  docs/guide/ai/bank-fraud-solution-content.md
  docs/guide/azure-sandbox/azure-sandbox-content.md
  docs/guide/iot-edge-vision/user-interface.md
  docs/guide/multitenant/approaches/resource-organization-content.md
  docs/guide/security/conditional-access-design-content.md
  docs/guide/technology-choices/microservices-assessment.md
  docs/high-availability/building-solutions-for-high-availability-content.md
Labels: ready-to-merge, review-team-triage, needs-human-review

#4348 Update data-protection-kubernetes-astra-azure-netapp-files-content.md
  docs/example-scenario/file-storage/data-protection-kubernetes-astra-azure-netapp-files-content.md
Labels: do-not-merge, review-team-triage

#4363 [Update] Rate Limiting Pattern Updated with Java Sample Link
  docs/patterns/rate-limiting-pattern-content.md
Labels: ready-to-merge, review-team-triage, qualifies-for-auto-merge

#4364 Update: Removed note stating partitioning is not available on Premium SKU
  docs/guide/multitenant/service/service-bus.md
Labels: Change sent to author, ready-to-merge, architecture-center/svc, azure-guide/subsvc, qualifies-for-auto-merge

#4366 Update. Added Bulkhead pattern reference to "Isolate critical resources"
  docs/guide/design-principles/self-healing.md
Labels: Change sent to author, ready-to-merge, architecture-center/svc, guide/subsvc, qualifies-for-auto-merge

#4369 Update services.md
  docs/aws-professional/services.md
Labels: Change sent to author, ready-to-merge, architecture-center/svc, cloud-fundamentals/subsvc, aq-pr-triaged, qualifies-for-auto-merge, pending-content-team/business-approval
