Repository MicrosoftDocs/architecture-center, pull requests merged in 2025-03, with the labels that each got.

#4642 Link to an example of poison message handling
  docs/patterns/competing-consumers-content.md
Labels: ready-to-merge, aq-pr-triaged, review-team-triage, pending-content-team/business-approval

#4643 Update: Fix typo: Azure key vault -> Azure Key Vault
  docs/ai-ml/architecture/baseline-openai-e2e-chat-content.md
  docs/ai-ml/guide/azure-openai-gateway-custom-authentication-content.md
  docs/web-apps/app-service/architectures/baseline-zone-redundant-content.md
  docs/web-apps/guides/networking/access-multitenant-web-app-from-on-premises-content.md
Labels: ready-to-merge, review-team-triage

#4644 Update - Update big-data-architectures-content.md
  docs/databases/guide/big-data-architectures-content.md
Labels: do-not-merge, review-team-triage

#4645 Update - Update azure-local-dr-content.md
  docs/hybrid/azure-local-dr-content.md
Labels: do-not-merge, review-team-triage

#4648 Update - Update circuit-breaker-content.md
  docs/patterns/circuit-breaker-content.md
Labels: do-not-merge, review-team-triage

#4649 Update - Update baseline-openai-e2e-chat-content.md
  docs/ai-ml/architecture/baseline-openai-e2e-chat-content.md
Labels: do-not-merge, review-team-triage

#4647 Update - Update extend-mainframe-applications-content.md
  docs/example-scenario/mainframe/extend-mainframe-applications-content.md
Labels: do-not-merge, review-team-triage

#4650 Update hub-spoke-content.md
  docs/networking/architecture/hub-spoke-content.md
Labels: ready-to-merge, aq-pr-triaged, review-team-triage
